version: "3.9"
services:
  backend:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - 8000:8000
    volumes:
      - .:/app
    depends_on:
      - mysqldb

  mysqldb:
    image: mysql:5.7.34
    restart: always
    environment:
      MYSQL_DATABASE: mydb
      MYSQL_USER: django
      MYSQL_PASSWORD: djangopass
      MYSQL_ROOT_PASSWORD: mysecretpassword
    volumes:
      - .dbdata:/var/lib/mysql
    ports:
      - 3306:3306
